max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
edition = "2021"
format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
format_macro_rewrites = true
format_derive = true
format_imports = true
format_imports_groups = true
format_imports_indent = "Block"
format_imports_separator = "Newline"
format_imports_sort = true
format_imports_merge_globs = true
format_imports_group_by = "StdExternalCrate"
format_imports_newline_style = "Unix"
format_imports_use_small_heuristics = "Default"
format_imports_use_field_init_shorthand = true
format_imports_use_struct_literal_syntax = true
format_imports_use_try_shorthand = true
format_imports_use_question_mark = true
format_imports_use_question_mark_chain = true
format_imports_use_question_mark_chain_allow_trailing = true
format_imports_use_question_mark_chain_allow_trailing_comma = true
format_imports_use_question_mark_chain_allow_trailing_semicolon = true
format_imports_use_question_mark_chain_allow_trailing_question_mark = true
format_imports_use_question_mark_chain_allow_trailing_question_mark_chain = true
format_imports_use_question_mark_chain_allow_trailing_question_mark_chain_allow_trailing = true
format_imports_use_question_mark_chain_allow_trailing_question_mark_chain_allow_trailing_comma = true
format_imports_use_question_mark_chain_allow_trailing_question_mark_chain_allow_trailing_semicolon = true
format_imports_use_question_mark_chain_allow_trailing_question_mark_chain_allow_trailing_question_mark = true
format_imports_use_question_mark_chain_allow_trailing_question_mark_chain_allow_trailing_question_mark_chain = true 